aliases: []
creation_timestamp: 1729785862722
current_stage: None
description: null
last_updated_timestamp: 1729785862722
name: tracking
run_id: 4585202bbcf049d391f2cce416b9058c
run_link: null
source: mlflow-artifacts:/0/4585202bbcf049d391f2cce416b9058c/artifacts/iris_model
status: READY
status_message: null
storage_location: mlflow-artifacts:/0/4585202bbcf049d391f2cce416b9058c/artifacts/iris_model
user_id: null
version: 1
