aliases: []
creation_timestamp: 1729786364056
current_stage: None
description: null
last_updated_timestamp: 1729786364056
name: tracking
run_id: 68c5fda4d61f439f8f7cf172982e3e04
run_link: null
source: mlflow-artifacts:/0/68c5fda4d61f439f8f7cf172982e3e04/artifacts/iris_model
status: READY
status_message: null
storage_location: mlflow-artifacts:/0/68c5fda4d61f439f8f7cf172982e3e04/artifacts/iris_model
user_id: null
version: 2
